### ISSUE TITLE
Composer should not import an abandoned package

### ISSUE THREAD

**Issue by notaphplover** [ckfinder/ckfinder-symfony3-bundle#1]
The composer.json requires "aws/aws-sdk-php": "~2.8.31", but that version of the package requires " guzzle/guzzle", which is abandoned. Could it be posible to use aws/aws-sdk-php 3 versions that points to the guzzlehttp/guzzle package instead?

**Comment by mtaylor456** [comment]
As above, aws has since moved to guzzle 6, is there any reason why this is stuck on 2.8?

**Comment by zaak** [comment]
@notaphplover, @mtaylor456: Fixed in newest version 3.4.2.
