### ISSUE TITLE
Symfony 4 Support

### ISSUE THREAD

**Issue by BoShurik** [ckfinder/ckfinder-symfony3-bundle#7]
Is there a plans to add support for Symfony 4?

**Comment by zaak** [comment]
Hi @BoShurik. Not yet. I believe that adding support for Symfony 4 should't require too much work though.

**Comment by jcarriere** [comment]
Do you know an other module ?

**Comment by zaak** [comment]
Just to let you know guys. `ckfinder/ckfinder-symfony3-bundle` package has been deprecated, for S4 please use [ckfinder/ckfinder-symfony-bundle](https://github.com/ckfinder/ckfinder-symfony-bundle).
